### PR TITLE
upgrading packages

### PR DESCRIPTION
**Pull request by llbbl**
Goal was to upgrade to the latest react. 

- I had to remove nightmare because kept wanting to install Electron, wouldn't work with it included
- moved babel/cli/core to supported versions
- removed node-sass because not supported so using newer dart/node version now
- changed a bit under scripts. not all of them working yet fyi. 

I bumped the version to 2.0.0, since all dependencies were bumped to major versions. 

*npm install works fine*

### CODE REVIEW

**Comment by llbbl** [comment]
This PR will get rid of 7 other dependabot Pull requests 🥇

**Comment by V3ntus** [comment]
Bump. Please bump the react peerDep's

**Comment by llbbl** [comment]
@V3ntus I ran npm upgrade and bumped stuff.  The react peerDeps can't be updated any more -- not sure what you meant? React 18.3 isn't out yet.

**Comment by V3ntus** [comment]
> The react peerDeps can't be updated any more -- not sure what you meant?

Sorry! Meant to direct that at the maintainer. "If nothing else, at least please bump peerDeps"

**Comment by grantbriston** [comment]
Sorry guys but I can't wait around, so i've published this as a new package

https://www.npmjs.com/package/react-modal-video-new

**Comment by mutschelknauss** [comment]
Thanks @llbbl for this PR. 

Would be great to have this PR merged in. We are getting console errors & warnings in this otherwise great project due to the lack of React 18+ support.

**Comment by atsu666** [comment]
Thanks @llbbl for this PR.

**Pull request merged**
